// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package outboxsql

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEvent struct {
	EventID       uuid.UUID          `json:"event_id"`
	SourceService string             `json:"source_service"`
	EventType     string             `json:"event_type"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	AggregateID   pgtype.Text        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	LastError     pgtype.Text        `json:"last_error"`
}

type OutboxEvent struct {
	EventID          uuid.UUID          `json:"event_id"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      uuid.UUID          `json:"aggregate_id"`
	EventType        string             `json:"event_type"`
	Payload          []byte             `json:"payload"`
	Headers          []byte             `json:"headers"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DeliveryAttempts int32              `json:"delivery_attempts"`
	LastError        pgtype.Text        `json:"last_error"`
	LockToken        pgtype.Text        `json:"lock_token"`
	LockedAt         pgtype.Timestamptz `json:"locked_at"`
}
